### ISSUE TITLE
Cannot build containers in demo-rollup example

### ISSUE THREAD

**Issue by evchip** [Sovereign-Labs/sovereign-sdk#1159]
## Summary
`make start` command fails in `examples/demo-rollup` with error:

```
Error response from daemon: Mounts denied: 
The path /credentials is not shared from the host and is not known to Docker.
```

I've checked and ensured that the `/credentials` path is shared.

## Steps to reproduce

* Use `nightly` branch of this repo
* Mac M1 with MacOS Monterey
* Use Docker Desktop 4.25.1
* Run `make start` in `examples/demo-rollup`

## Expected Result
Successfully run containers `docker-sequencer-0-1` and `docker-validator-1`

## Actual Result
```
➜  demo-rollup git:(nightly) make start
Starting local celestia network setup
/bin/sh: line 0: test: : integer expression expected
[+] Building 65.7s (23/23) FINISHED                                                                                                                                       docker:desktop-linux
 => [sequencer-0 internal] load build definition from Dockerfile.bridge                                                                                                                  10.1s
 => => transferring dockerfile: 560B                                                                                                                                                     10.0s
 => [sequencer-0 internal] load .dockerignore                                                                                                                                            10.1s
 => => transferring context: 2B                                                                                                                                                          10.0s
 => [validator internal] load .dockerignore                                                                                                                                              10.1s
 => => transferring context: 2B                                                                                                                                                          10.0s
 => [validator internal] load build definition from Dockerfile.validator                                                                                                                 10.1s
 => => transferring dockerfile: 530B                                                                                                                                                     10.0s
 => [validator internal] load metadata for ghcr.io/celestiaorg/celestia-app:v1.0.0                                                                                                       21.6s
 => [sequencer-0 internal] load metadata for docker.io/library/alpine:3.18.3                                                                                                             25.4s
 => [sequencer-0 internal] load metadata for ghcr.io/celestiaorg/celestia-node:v0.11.0-rc15                                                                                              21.6s
 => [validator auth] celestiaorg/celestia-app:pull token for ghcr.io                                                                                                                      0.0s
 => [sequencer-0 auth] celestiaorg/celestia-node:pull token for ghcr.io                                                                                                                   0.0s
 => [sequencer-0 auth] library/alpine:pull token for registry-1.docker.io                                                                                                                 0.0s
 => [validator stage-0 1/4] FROM docker.io/library/alpine:3.18.3@sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a                                                  0.0s
 => [validator internal] load build context                                                                                                                                              10.0s
 => => transferring context: 5.57kB                                                                                                                                                      10.0s
 => [validator] FROM ghcr.io/celestiaorg/celestia-app:v1.0.0@sha256:41d042a00d1adcdde1c038f5f3c82cc122e0d64c00f47e58ff856764795f5324                                                      0.0s
 => [sequencer-0 internal] load build context                                                                                                                                            10.0s
 => => transferring context: 2.19kB                                                                                                                                                      10.0s
 => [sequencer-0] FROM ghcr.io/celestiaorg/celestia-node:v0.11.0-rc15@sha256:077b585d37d470b68eeb17cbe50a7555e6e89a3b6161d73f06eb5f0d280b990c                                             0.0s
 => CACHED [validator stage-0 2/4] RUN apk update && apk add --no-cache bash jq                                                                                                           0.0s
 => CACHED [sequencer-0 stage-0 3/5] COPY --from=ghcr.io/celestiaorg/celestia-node:v0.11.0-rc15 /bin/celestia /bin/celestia                                                               0.0s
 => CACHED [sequencer-0 stage-0 4/5] COPY --from=ghcr.io/celestiaorg/celestia-node:v0.11.0-rc15 /bin/cel-key /bin/cel-key                                                                 0.0s
 => CACHED [sequencer-0 stage-0 5/5] COPY ./run-bridge.sh /opt/entrypoint.sh                                                                                                              0.0s
 => [sequencer-0] exporting to image                                                                                                                                                      0.0s
 => => exporting layers                                                                                                                                                                   0.0s
 => => writing image sha256:b3402a1c55eaf5e3bec5a72a0dfd881429881edcae04d4cde65a7bbe56fe39ec                                                                                              0.0s
 => => naming to docker.io/library/bridge                                                                                                                                                 0.0s
 => CACHED [validator stage-0 3/4] COPY --from=ghcr.io/celestiaorg/celestia-app:v1.0.0 /bin/celestia-appd /bin/celestia-appd                                                              0.0s
 => CACHED [validator stage-0 4/4] COPY ./run-validator.sh /opt/entrypoint.sh                                                                                                             0.0s
 => [validator] exporting to image                                                                                                                                                        0.0s
 => => exporting layers                                                                                                                                                                   0.0s
 => => writing image sha256:67b4fe240079b6db6b0ac1d4253c8ba1b8c820e5259615a59428b25fa8fa830d                                                                                              0.0s
 => => naming to docker.io/library/validator                                                                                                                                              0.0s
[+] Running 2/2
 ✔ Container docker-sequencer-0-1  Recreated                                                                                                                                              0.0s 
 ✔ Container docker-validator-1    Recreated                                                                                                                                              0.0s 
Error response from daemon: Mounts denied: 
The path /credentials is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/desktop/mac for more info.
make: *** [start-network] Error 1
```

## Additional Information
`docker/credentials` is contained within `Users` directory, which is shared:
<img width="587" alt="image" src="https://github.com/Sovereign-Labs/sovereign-sdk/assets/42247026/15542897-1657-46fd-b7a3-f6fab63c89a1">

**Comment by bkolad** [comment]
Hey it looks like a problem with docker, can you please set: `export DOCKER_DEFAULT_PLATFORM=linux/amd64`

**Comment by evchip** [comment]
>  Hey it looks like a problem with docker, can you please set: export DOCKER_DEFAULT_PLATFORM=linux/amd64

@bkolad Hey, thanks for the quick response. Unfortunately that didn't work for me. I'm getting the same error.

I can try to run it on a Linux machine if you think I'd have more luck?

**Comment by bkolad** [comment]
Our `CI` works with linux and we test the `Celestia` setup there. This led me to believe that the issue may be related to Docker on Mac. However, we are still in the process of reproducing and investigating it. Feel free to try linux.

**Comment by citizen-stig** [comment]
Hey @youngkashew 

We haven't been able to reproduce your issue so far, but in the meantime I can offer you a couple options:


## Option 1, absolute path to credentials dir


To 100% eliminate path mapping shenaningans , can you replace `./credentials` in `sovereign-sdk/docker/docker-compose.yml` in the volumes section at the bottom of the file with absolute path on on your system? 

```yml
volumes:
  # local volume where sequencer's credentials can 
  credentials:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
     # Should become something like this
      device: '/Users/your_username/something/sovereign-sdk/docker/credentials'
 ```
 
 
Based on the error message, `The path /credentials is not shared from the host and is not known to Docker.` it looks like docker resolves this path from the `/`, which is weird. Maybe there's problem in the Makefile.
 
 
## Option 2: Downgrade docker

Some of our engineers had a problem with Docker Desktop on M1 Monterrey after upgrading to 4.25.

## Option 3: Check filesystem permission

To eliminate another problem, please make sure, that user who runs docker have file system access to folder where repo is checked out. Potentially if it different users, this might be the problem.

**Comment by dubbelosix** [comment]
@youngkashew in addition to the steps that @citizen-stig outlined - 
To rule out if its a docker permissions issue, can you try running this command from the `examples/demo-rollup` folder
```
CREDENTIALS_DIR="$(git rev-parse --show-toplevel)/docker/credentials" && docker run --rm -v "$CREDENTIALS_DIR":/credentials alpine ls /credentials
```
if there are no permission issues, then it should print the contents of the folder - 
```
bridge-0.addr
bridge-0.key
```

**Comment by evchip** [comment]
@citizen-stig and @dubbelosix thanks for the suggestions.
1. I set the absolute path to the credentials directory in the `docker-compose.yml` file - no change
2. Tried downgrading Docker to 4.24 and 4.22 but am receiving [an error](https://github.com/docker/for-mac/issues/6294) that doesn't allow me to even open the app. I'll try updating my OS to the latest version to see if that fixes the compatibility issues.
3. The user who runs Docker does indeed have file system access to the folder where the repo is checked out.

@dubbelosix I ran the command and it printed out the contents of the folder as you pasted it.

**Comment by evchip** [comment]
> Tried downgrading Docker to 4.24 and 4.22 but am receiving https://github.com/docker/for-mac/issues/6294 that doesn't allow me to even open the app. I'll try updating my OS to the latest version to see if that fixes the compatibility issues.

I was able to use 4.22 after updating my OS, but the error persists.

**Comment by evchip** [comment]
Still getting the same issue on MacOS, but happy to report that I got the demo-rollup example running on a Linux machine. 

Initially was facing errors: 
```
ERROR: for docker_sequencer-0_1 Cannot start service sequencer-0: error while mounting volume '/var/lib/docker/volumes/docker_credentials/_data': failed to mount local volume: mount /home/ubuntu/sovereign-sdk/examples/demo-rollup/credentials:/var/lib/docker/volumes/docker_credentials/_data, flags: 0x1000: no such file or directory
```

However I fixed this by replacing `./credentials` in `sovereign-sdk/docker/docker-compose.yml` in the volumes section at the bottom of the file with absolute path.

**Comment by citizen-stig** [comment]
@youngkashew , so it looks like it is not a Docker version issue, but volume resolution related.

Can you try to run `docker volume inspect docker_credentials` after trying to run `make start` without your fix?

**Comment by evchip** [comment]
> `docker volume inspect docker_credentials`

I get this output:
```
[
    {
        "CreatedAt": "2023-10-26T09:58:31Z",
        "Driver": "local",
        "Labels": {
            "com.docker.compose.project": "docker",
            "com.docker.compose.version": "2.7.0",
            "com.docker.compose.volume": "credentials"
        },
        "Mountpoint": "/var/lib/docker/volumes/docker_credentials/_data",
        "Name": "docker_credentials",
        "Options": {
            "device": "./credentials",
            "o": "bind",
            "type": "none"
        },
        "Scope": "local"
    }
]
```

**Comment by dubbelosix** [comment]
@youngkashew it seems like the docker volume is not being created with the correct path. 
```
"Mountpoint": "/var/lib/docker/volumes/docker_credentials/_data",
```
is not the right path, since it should be the credentials folder in the repository. I believe once docker creates a volume, it won't re-create it even with `--force-recreate` flags, so they need to be manually deleted. this issue might happen if the volume is created once with the wrong path, and is not corrected unless the volume is deleted

could you manually delete both the volumes and then re-try
list the volumes
```
 % docker volume ls                                                          
DRIVER    VOLUME NAME
local     docker_credentials
local     docker_genesis
```
and then you can delete with
```
docker volume rm docker_credentials
docker volume rm docker_genesis
```
this time when you use make start or the docker compose command, the volume should be re-created and you can check if the "Mountpoint" attribute when you inspect docker_credentials has the absolute path to the credentials folder in the repo

EDIT: could you also change the mount section of the compose file to include an absolute path to the repo credentials folder (under volumes : credentials : device section of the compose yml

**Comment by evchip** [comment]
@dubbelosix yep, that worked. Thanks for your help!

**Comment by zvolin** [comment]
Hey,

The mountpoint path is correct, note that in case of macbook it points to the linux vm of docker, there is no such path in your host directly.
```json
"Mountpoint": "/var/lib/docker/volumes/docker_credentials/_data",
```

The issue is the device used, docker should resolve it to the fullpath by itself. So the faulty one (the one reported by @youngkashew) persists the relative path:
```json
"Options": {
    "device": "./credentials",
    "o": "bind",
    "type": "none"
},
```
while the correct, expected one should be:
```json
"Options": {
    "device": "/data/eiger/celestia/sovereign-sdk/docker/credentials",
    "o": "bind",
    "type": "none"
},
```

I'm able to reproduce that behavior after removing the `o: 'bind'` from the `docker-compose.yml` however that is not the case here as we can see it present in the output of the `docker inspect`. Running on a clean repo I can't reproduce this and I get the expected output on both MacOS Ventura and Sonoma and archlinux 6.6.1.

One thing you could check is to update your docker compose plugin as it seems quite old.

```json
"Labels": {
    "com.docker.compose.project": "docker",
    "com.docker.compose.version": "2.7.0",
    "com.docker.compose.volume": "credentials"
},
```

I don't think setting up full paths inside `docker-compose.yml` is a proper solution tho. It either requires some hacks to automate it or is a manual action we require from users, both don't seem great. I have no idea what caused the volume to be created in invalid way at first but I suspect that those are either related to some local modifications or outdated tools. Are you able to reproduce it @youngkashew?

**Comment by evchip** [comment]
> Are you able to reproduce it @youngkashew?

@zvolin I cleaned my environment and tried to follow the steps that led me to the issue to the best of my recollection, but couldn't replicate it again. I don't believe I made any local modifications when I encountered the issue. I did downgrade Docker from 4.25 as recommended by @citizen-stig, but that did not seem to affect the issue.

**Comment by zvolin** [comment]
Heisenbug
