### ISSUE TITLE
Unable to get a token's total supply

### ISSUE THREAD

**Issue by LiveDuo** [Sovereign-Labs/sovereign-sdk#1239]
I've been experimenting with the SDK trying and had the following issue.

In an attempt to build a voting module I was unable to get the total supply of a token and determine the token holder "voting power".

```rs
# this works
let sender_votes = self.bank.get_balance_of(sender_address, token_address, working_set).unwrap_or(0);
# this does not
let total_supply = self.bank.supply_of(token_address, working_set).unwrap();
```

Looking into the `sov-bank` source code I noticed that the [supply_of](https://github.com/Sovereign-Labs/sovereign-sdk/blob/9fee11f0ee71acf25f4bab97e24c99200a632bc0/module-system/module-implementations/sov-bank/src/query.rs) method is behind the `native` feature flag which is not accessible onchain while [get_balance_of ](https://github.com/Sovereign-Labs/sovereign-sdk/blob/9fee11f0ee71acf25f4bab97e24c99200a632bc0/module-system/module-implementations/sov-bank/src/call.rs#L251) method is not.

Is there a way to access a token's [total_supply](https://github.com/Sovereign-Labs/sovereign-sdk/blob/9fee11f0ee71acf25f4bab97e24c99200a632bc0/module-system/module-implementations/sov-bank/src/token.rs#L113) onchain without creating a custom bank module? Maybe accessing the state directly since there's no `supply_of` method in the zk context?

**Comment by bkolad** [comment]
Thanks for reporting. We will make the method accessible on-chain.

**Comment by LiveDuo** [comment]
Thank you!

**Comment by bkolad** [comment]
The relevant PR is here: https://github.com/Sovereign-Labs/sovereign-sdk/pull/1240 and will be merged soon. Will this work for you?

**Comment by LiveDuo** [comment]
That's exactly it! Glad it'll be in the `sov-bank` module and won't have to create a custom one.
