### ISSUE TITLE
Delete `ReadOnlyLock` in favor of just `Arc`

### ISSUE THREAD

**Issue by neysofu** [Sovereign-Labs/sovereign-sdk#1302]
## Summary

`ReadOnlyLock` doesn't offer any functionality over a bare `Arc`; let's delete it from the codebase and just use `Arc`.

**Comment by citizen-stig** [comment]
Discussed during the call, that ReadOnlyLock suppose only clone of Arc<RwLock<T>>, where "original" Arc can do writing.
