### ISSUE TITLE
Test bank RPC methods

### ISSUE THREAD

**Issue by preston-evans98** [Sovereign-Labs/sovereign-sdk#190]
Add tests for the `bank_balanceOf` rpc method, and any additional methods that we expose. Blocked on #189

**Comment by citizen-stig** [comment]
With https://github.com/Sovereign-Labs/sovereign-sdk/pull/372, https://github.com/Sovereign-Labs/sovereign-sdk/pull/347 and https://github.com/Sovereign-Labs/sovereign-sdk/pull/278/ it looks like bank testing is pretty well covered.

@preston-evans98 could you please elaborate what is expected from this issue?
