### ISSUE TITLE
Bank Module: Allow minting after token deployment.

### ISSUE THREAD

**Issue by citizen-stig** [Sovereign-Labs/sovereign-sdk#195]
> * All tokens in current implementation are fixed supply, there's no way to mint new tokens after token is deployed. Is it intended?

I think this was intentionally left out-of-scope for the initial implementation, but that we always planned to add it eventually. @bkolad, am I remembering that right?

_Originally posted by @preston-evans98 in https://github.com/Sovereign-Labs/sovereign/issues/183#issuecomment-1520348269_

**Comment by bkolad** [comment]
Yes we left out this functionality for now. Should we include it for the next milestone?

**Comment by citizen-stig** [comment]
@dubbelosix , I believe this issue has been resolved in scope of #347 

Is there something else left? If no, could you please close this issue?

**Comment by dubbelosix** [comment]
yup, it can be closed since now we can mint, burn from the bank module. closing it
