### ISSUE TITLE
Discussion: Custom macro expander

### ISSUE THREAD

**Issue by preston-evans98** [Sovereign-Labs/sovereign-sdk#198]
## Background
Currently, we try to avoid surfacing macro-generated code to users because it isn't easily viewable. AFAIK, there are currently two popular workarounds for this issue: 
1. Use `cargo expand`
2. View generated code in rustdoc

Neither workaround is ideal. The output of `cargo expand` is extremely cluttered, because *all* macros are expanded. This includes implementation of `Serde`, `Clone`, `Copy`, `PartialEq`, etc for numerous types. Even worse, many of these extraneous expansions are not intended to be easily viewable - and the generated output cannot be easily fed into a language server. On the other hand, Rustdoc doesn't provide nearly enough visibility into the generated output.

Ideally, Sovereign macros would result in output that is searchable/discoverable, and which can be fed into a language server. As a building block, we can trivially cause Sovereign's macros to output their expansions to text files. 

A very rough sketch of what this might look like is. 

```
pub(crate) fn derive_rpc(
    attrs: proc_macro2::TokenStream,
    input: syn::ItemImpl,
) -> Result<proc_macro2::TokenStream, syn::Error> {
    let type_name = match *input.self_ty {
        syn::Type::Path(ref type_path) => &type_path.path.segments.last().unwrap().ident,
        _ => return Err(syn::Error::new_spanned(input.self_ty, "Invalid type")),
    };

    let mut expansion = build_rpc_trait(&attrs, type_name.clone(), input)?;
    if  env::var("SOV_EXPAND_MACROS").is_ok() { 
      let out_file = fs::open(format!("./{}_rpc_expanded.rs", type_name), ...);, 
      out_file.write(expansion.to_string());
     let module_name = format!("./{}_rpc_expanded.rs", type_name); 
      expansion = quote! { 
        #commented_original_code
        mod #module_name; 
        pub use #module_name::*
      }
    } 
}

```

The end result of this would be that users could set an environment variable "SOV_EXPAND_MACROS", which would cause the output of macros to be placed dropped into their source code repository and "wired up" so that it was discoverable by both humans and IDEs. 

@bkolad  @citizen-stig, curious for your thoughts

**Comment by bkolad** [comment]
Good idea, but I would like to highlight some additional work:
1. It would be good to test the expansion in the CI
2. The `wiring` mechanism should work even if we refactor/move code around so the macros won't stop us from refactoring.

Another idea:
Wahy if we look at how  `cargo expand` is implemented, maybe we could have `cargo sov-expand` that expands only sov macros in the terminal. We woule have to figure out a way to tag and filter our macros.
