### ISSUE TITLE
Implement no_std support

### ISSUE THREAD

**Issue by preston-evans98** [Sovereign-Labs/sovereign-sdk#20]
### Background
Although Risc0 supports std, many (most?) zkVMs and compilers will not. To accommodate these, we should support `no_std` in the SDK. 

- Consider using a type alias for Arc/Rc which conditionally enables atomics depending on a compiler flag (so that we can use it both inside and outside of the zkvm)
- Use `maybestd` where possible. For types not covered by maybestd, re-export them from a module and point all imports there. This way, we automatically switch between `core` and `std` at compile time.
- Consider creating a custom crate for collections instead of using `std::collections` so that we can easily swap to optimized primitives and avoid dependencies on libraries with compatibility issues (like `once_cell` and `ahash`)

**Comment by DaviRain-Su** [comment]
`thiserror` present is not support `no_std`, suggest use `displaydoc` to replace with `thiseeror`.

**Comment by citizen-stig** [comment]
After many iterations of discussions, `no_std` requirement is quite brutal and in reality is not needed by existing zkVM frameworks. 

I would suggest to close this issue to avoid confusion.

It might be that some parts of SDK will be no_std, but not whole framework.
