### ISSUE TITLE
Remove `jmt` dependency from SDK package

### ISSUE THREAD

**Issue by preston-evans98** [Sovereign-Labs/sovereign-sdk#225]
Currently, the Sovereign SDK re-exports the `jmt` package and exposes one trait which depends on it (`TreeWitnessReader`). Since the SDK is supposed to be agnostic about what state commitment is used by implementers, we should remove that dependency. We should be able to move all of the relevant functionality into the `sov-state` package.

**Comment by preston-evans98** [comment]
@citizen-stig suggests that we should replace `SimpleHasher` with https://docs.rs/digest/latest/digest/trait.Digest.html. I think that's a good idea, since `Digest` is more standard

**Comment by citizen-stig** [comment]
@preston-evans98 actually it is your idea and I am totally onboard with that.
