### ISSUE TITLE
Update jmt to remove honest treereader assumption.

### ISSUE THREAD

**Issue by preston-evans98** [Sovereign-Labs/sovereign-sdk#246]
Currently, the JMT supports trustless proof verification but it does *not* support trustless updates. Specifically, there's currently no way to enforce that every sibling hash in an updated merkle tree is the same as the sibling hash in the old merkle tree *in the absence of a trusted treereader`. To fix this, we need to prove the correctness of every sibling hash used to compute the new merkle root against the old merkle root.

**Comment by erwanor** [comment]
Released in `jmt@0.7.0` https://crates.io/crates/jmt/0.7.0
