### ISSUE TITLE
Revert entire batch if sequencer is malicious

### ISSUE THREAD

**Issue by preston-evans98** [Sovereign-Labs/sovereign-sdk#249]
When a sequencer includes a structurally invalid transaction in a batch, the entire batch should be reverted in sov-a. Currently, only the invalid transaction is reverted. Blocked on #247

**Comment by citizen-stig** [comment]
I think it is not the case anymore, with implementing sequencer registry and all transactions are verified statelessly before checking state.

@preston-evans98 please confirm if it can be closed
