### ISSUE TITLE
Consider adding a Zkvm type to Spec

### ISSUE THREAD

**Issue by preston-evans98** [Sovereign-Labs/sovereign-sdk#281]
> Can we move Vm inside Spec and access it via Context? We do this with PublicKey, Address etc.. types. It will make it more uniform, and it is simpler in the macros to deal with only one generic (otherwise, we will need to update the Dispatch macros for runtime). In this approach, it would be the implementer of the Spec ((Zk)DefaultContext) who would choose the concrete Zkvm and we won't have to pass the Vm generic everywhere.

**Comment by citizen-stig** [comment]
I believe this is not relevant anymore. @preston-evans98 feel free to reopen
