### ISSUE TITLE
deriving `ModuleInfo` for multiple structs errors out due to dup imports

### ISSUE THREAD

**Issue by dubbelosix** [Sovereign-Labs/sovereign-sdk#291]
the following sample code 

```
#[derive(ModuleInfo)]
pub struct TestStruct<C: Context> {
    #[address]
    pub(crate) address: C::Address,
}

#[derive(ModuleInfo)]
pub struct AnotherStruct<C: Context> {
    #[address]
    pub(crate) address: C::Address,
}

```

in the same file causes a compile error

```
error[E0252]: the name `AddressTrait` is defined multiple times
  --> src/test_struct.rs:34:10
   |
28 | #[derive(ModuleInfo)]
   |          ---------- previous import of the trait `AddressTrait` here
...
34 | #[derive(ModuleInfo)]
   |          ^^^^^^^^^^ `AddressTrait` reimported here
```

likely due to https://github.com/Sovereign-Labs/sovereign/blob/research/sov-modules/sov-modules-macros/src/module_info.rs#L127 which introduces duplicate imports

temp workaround is to have structs in their own rust modules and not have two ModuleInfo annotations in the same module.

**Comment by citizen-stig** [comment]
Might be fixed by #636 , need to double check
