### ISSUE TITLE
Create Default Tx Hooks and Default Tx Verifier

### ISSUE THREAD

**Issue by preston-evans98** [Sovereign-Labs/sovereign-sdk#319]
Using hooks is an advanced feature for modules. While a few special modules like accounts and sequencer need access to hooks, most modules will not. So, we should consider making moving the current DemoTxHooks and DemoTxVerifier into another package and exporting them as default values.

cc @bkolad, curious for your thoughts here

**Comment by cemozerr** [comment]
For demo-stf, this would definitely improve readability.

**Comment by bkolad** [comment]
what if we put the default hooks in `module-implementations/default_hooks` and import them in `demo-stf`. This means that `module-implementations` contains modules + some other module related code.
