### ISSUE TITLE
Implement Send Transaction RPC

### ISSUE THREAD

**Issue by preston-evans98** [Sovereign-Labs/sovereign-sdk#357]
The Sovereign full node should have an RPC endpoint which accepts transactions on behalf of end-users. This RPC mode should be optional and enabled by a config setting. 

The endpoint should...
- Accept encoded transactions in the format generated by our `bank-cmd` tool (binary?). 
- Run stateless verification on the transaction. If stateless verification fails, return a descriptive error
- (Eventually) Check that the nonce of the transaction has not already been used. if it has, return a descriptive error.
- Add the transaction to the pending pool

**Comment by citizen-stig** [comment]
> Run stateless verification on the transaction. If stateless verification fails, return a descriptive error

Should RPC node has it's own verification or should this verification added to `BatchBuilder?

> (Eventually) Check that the nonce of the transaction has not already been used. if it has, return a descriptive error.

What state should be checked? Should it be nonce from commited state, or nonces in mempool? 

> Add the transaction to the pending pool

Is pending pool same as mempool in `BatchBuilder` or is it separate pool and some another routine moves from one to another?

@preston-evans98 @bkolad @dubbelosix
