### ISSUE TITLE
Bug in `token::mint`

### ISSUE THREAD

**Issue by bkolad** [Sovereign-Labs/sovereign-sdk#369]
[Here](https://github.com/Sovereign-Labs/sovereign-sdk/blob/main/module-system/module-implementations/sov-bank/src/token.rs#L101) we add `total_supply` and `amount`, this can overflow.  Instead of `+`  we should use [checked_add](https://doc.rust-lang.org/std/primitive.u32.html#method.checked_add) . 
The `transfer` method is fine as we can't have account with more tokens than `total_supply`.

We should also add a unit test for this case.

**Comment by preston-evans98** [comment]
@dubbelosix, this looks like it was closed by #372. Is there any remaining work?
