### ISSUE TITLE
Bug: db.get_batches method in ledger rpc

### ISSUE THREAD

**Issue by theochap** [Sovereign-Labs/sovereign-sdk#393]
[###](url) How to reproduce the bug
I encountered the following bug while testing the ledger RPC module. In the theo/test_rpc branch, in the test_rpc.rs file, the fourth test case: 
```rust
let data = r#"{"jsonrpc":"2.0","method":"ledger_getBatches","params":[[2], "Standard"],"id":1}"#
            .as_bytes();
let expected = r#"{"jsonrpc":"2.0","error":{"code":-32000,"message":"io error: unexpected end of file"},"id":1}"#;
query_test_helper(data, expected);
```
Highlights that the ledger_getBatches method returns an error message while being inputed the right parameters.

### Origin of the bug
In [ledger-db/rpc.rs](https://github.com/Sovereign-Labs/sovereign-sdk/blob/theo/tests-rpc/full-node/db/sov-db/src/ledger_db/rpc.rs)  in the populate_batch_response function we perform the following conversion:
```rust
batch.try_into?()
```
For each query mode, this conversion raises the error: (io error: unexpected end of file).

### Explanation
It seems that this bug is due to the fact that the StoredBatch and the BatchResponse structures don't have the same format (the BatchResponse has a tx_range field that StoredBatch doesn't have), hence the conversion is not straightforward.

**Comment by preston-evans98** [comment]
This looks like it's an error in the deserialization of the custom receipt - nothing else in `try_into` should be able to raise an `io error`. This likely indicates that the data being stored in the database is missing (part of) the custom `StoredBatch` field.

 Is it possible that we're trying to read a different type than we're writing?

**Comment by theochap** [comment]
Yes, I just figured it out and indeed I wasn't providing the right generic parameters to get_ledger_rpc, I am going to close the issue
