### ISSUE TITLE
`Genesis` cross-module dependencies.

### ISSUE THREAD

**Issue by citizen-stig** [Sovereign-Labs/sovereign-sdk#428]
# Description
If my module relies on another module in `genesis` logic, it might fail, as there are no strong guarantee that my depedency will be initialized at the moment of genesis of my module. 
It will work only if I declare modules in correct order in runtime, which implies that I, as developer, know dependencies of each module.

# Solutions

There are no clear the best solution, but only variants:

## Disallow dependencies on other modules

*pros:*

* Simpler logic

*cons:*

* Severely limits what can be done in genesis
* Require more compilcated configuration file
* Harder to enforce.

## Require genesis to be idempotent

This allow module explicitly call genesis for dependencies that really needed for genesis, and if it is already been called, nothing should happen.

*pros:*

* Modules can manage gensis themself

*cons:*

* Require developers to stick to contraint
* Big problem of passing configuration around.

## Keep manual order of modules, but make it more robust

Currently module genesises are called in order they declared in Runtime. 
This might be fine, except that there's possibility if calling module before genesis won't result in explicit error, but rather in implicit one.

For example, bank module and sequencer registry module. If bank module is not initialized, it will error on any operation, as balances are not preset. 
But what if some another module can operate without error before genesis. This means that if developer didn't order modules correctly, genesis of child module will pass, but it's changes might be overwritten by genesis of parent, which will result in broken state, which is hard to debug.

Solution might be similar to "idempotent" approach, where each module prevents calling any of its public methods before some boolean variable in state is initialized.

**Comment by LukaszRozmej** [comment]
Potential solution: 
Make module dependencies explicit (can be done using some `module_id`), then this would be easy to sort in runtime. Best case scenario we can generate these dependencies on a macro level, worst case scenario they should be set by the module developer. This would also be able to identify potential circular dependencies issues.
