### ISSUE TITLE
Move out custom rollup logic from `demo-rollup` and `demo-prover` 

### ISSUE THREAD

**Issue by citizen-stig** [Sovereign-Labs/sovereign-sdk#459]
Currently there's a lot of custom logic in demo-rollup and demo-prover, which is not covered by any test or structured. 

Since it is entry point for all sovereign SDK new users, it should be in normal crate, probably generic and configurable, and most important, tested.

And existing `demo-rollup` and `demo-prover` should be minimal, only loading configuration, logging and building other components.

**Comment by bkolad** [comment]
Implemented in: https://github.com/Sovereign-Labs/sovereign-sdk/pull/614
