### ISSUE TITLE
Sov-celestia-local container needs Dockerfile so that we can modify, update and build other versions of celestia binaries

### ISSUE THREAD

**Issue by dubbelosix** [Sovereign-Labs/sovereign-sdk#461]
## Summary

Currently sov-celestia-local is a hard baked image that is pushed to a public user dockerhub. This works for the single version that we currently use but cannot be customized, and developers/users cannot update the versions of the celestia binaries to test newer code. In order to solve this we want a Dockerfile that can build sov-celestia-local from scratch. The initial goal is just to have a file for 0.7.1 (the current version baked into sov-celestia-local)

**Comment by l-monninger** [comment]
What's the word on this? We noticed that emulation doesn't seem to work as we get the below on  M1 devices.

```
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

We're looking to make it easer for M1 devs to work on our rollup, so we'd love to at least have it compiled for arm64.
