### ISSUE TITLE
Remove `AlignedVec` placeholder

### ISSUE THREAD

**Issue by bkolad** [Sovereign-Labs/sovereign-sdk#47]
Certain `Vec` operations are cheaper in zk-context when done on a vector whose length is aligned to 4 bytes.
We should implement `AlignedVec` wrapper on `std::vec::Vec` that enforces this guarantee. 

We already have a stub for `AlignedVec ` in the code, but for now, it defaults to `std::vec::Vec`

**Comment by neysofu** [comment]
I'd suggest holding off on this, and possibly even removing `AlignedVec` unless we have numbers telling us that's clearly worth the hassle.

**Comment by citizen-stig** [comment]
Team agreed on removing AlignedVec
