### ISSUE TITLE
Implement proof publishing on chain

### ISSUE THREAD

**Issue by citizen-stig** [Sovereign-Labs/sovereign-sdk#494]
Specification states that proof batches should be published on chain.

This should be implemented. But this is also design task, because we need to decide if it is going to be different names space or same name space, but different encoding for bytes.

Potentially required tasks

* https://github.com/Sovereign-Labs/sovereign-sdk/issues/283
* https://github.com/Sovereign-Labs/sovereign-sdk/issues/459

**Comment by cemozerr** [comment]
Closing issue as AFAIK it was implemented.
