### ISSUE TITLE
EVM: Remove dependency on the `foundry` fork

### ISSUE THREAD

**Issue by bkolad** [Sovereign-Labs/sovereign-sdk#498]
Our dependency, the `foundry` crate, is encountering issues during the building process. see: https://github.com/foundry-rs/foundry/issues/5409.
To address this, we have implemented a temporary solution by forking the dependency and addressing the issue in pull request #496.
Once the changes from foundry-rs/foundry#5397 are merged, we should remove the dependencies on the fork.

**Comment by bkolad** [comment]
The changes ware merged in `foundry-rs` , upgrading our dependency causes the following error:
```
error[E0658]: use of unstable library feature 'is_terminal'
  --> /Users/blaze/.cargo/git/checkouts/foundry-f7cca724e93059b0/02e430c/common/src/term.rs:11:22
   |
11 |     io::{prelude::*, IsTerminal},
   |                      ^^^^^^^^^^
   |
   = note: see issue #98070 <https://github.com/rust-lang/rust/issues/98070> for more information
   = help: add `#![feature(is_terminal)]` to the crate attributes to enable

error[E0658]: use of unstable library feature 'is_terminal'
  --> /Users/blaze/.cargo/git/checkouts/foundry-f7cca724e93059b0/02e430c/common/src/term.rs:41:61
   |
41 |         TermSettings { indicate_progress: std::io::stdout().is_terminal() }
``` 

To be investigated.

**Comment by neysofu** [comment]
Starting from commit https://github.com/foundry-rs/foundry/commit/058182db5c220c12d585b10aff1d3dd17addc62b Foundry requires `rustc` 1.70, which stabilized `IsTerminal`. The last 1.69-compatible commit is https://github.com/foundry-rs/foundry/commit/e41318d1ce8862f5dfd86bc2bc177541e2731978.

**Comment by neysofu** [comment]
Fixed by https://github.com/sovereign-Labs/sovereign-sdk/pull/574.
