### ISSUE TITLE
EVM: Handle `EVMError` when the EVM execution fails

### ISSUE THREAD

**Issue by bkolad** [Sovereign-Labs/sovereign-sdk#505]
## Description
Currently, when the EVM execution fails, the code panics. We need to come up with a solution to handle these EVM errors appropriately.

## Acceptance Criteria
1. Ensure that no panics occur during unsuccessful EVM execution.
2. Implement unit tests to cover this specific case.

**Comment by bkolad** [comment]
The last question to answer is if failed tx should consume all gas.

**Comment by orkunkilic** [comment]
I think this was also related to eth_call so we can close @bkolad?
