### ISSUE TITLE
Re-export `jsonrpsee` and `serde_json` in `sov-modules-macros`

### ISSUE THREAD

**Issue by citizen-stig** [Sovereign-Labs/sovereign-sdk#524]
# Issue

Currently if user wants to generate RPC endpoints using `sov-modules-macro` they need to expcitly add `jsonrpsee` dependency of correct version. Which is adds unnecessart friction

# Suggested solution

`sov-modules-macro` re-exports `jsonrpsee` and in generated code references `sov_modules_marco::jsonrpsee` and not `jsonrpsee` directly.

**Comment by neysofu** [comment]
`schemars` too, and generally all dependencies used by the macros.

**Comment by citizen-stig** [comment]
Another one:

```
101 |     sov_modules_api::macros::CliWalletArg,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `clap` in the list of imported crates
    ```
