### ISSUE TITLE
module-system: New module structure

### ISSUE THREAD

**Issue by bkolad** [Sovereign-Labs/sovereign-sdk#536]
## Description
Here is the current module structure:
```
/src
  - lib.rs
  - call.rs
  - query.rs
  - genesis.rs
  - hooks.rs
```

The `call, query, genesis, and hooks` modules are currently public, but most of the code inside these modules, except for types, is private to the crate. However, the `#![deny(missing_docs)]` directive in `lib.rs` enforces documenting these modules (on the module level), even though most of the code is not visible.

To address this issue, the proposed solution is to make the modules private and reexport the necessary types in `lib.rs` as public types of the crate. This approach offers the following advantages:

1. The main documentation will reside in `lib.rs` (won't be spread across several files), and its content can be sourced from the `README.md` file using `#![doc = include_str!("../README.md")]`.
2. `call/query/..` don't need module level documentation anymore
3. Consumers of the modules will import only the root of the module, such as `sov_accounts::CallMessage`, instead of having to specify the full path like `sov_accounts::call::CallMessage`.
4. Structure of the module doesn't leak.

## Acceptance Criteria
1. All modules moved to the new structure
2. Relevant docs are updated.

**Comment by preston-evans98** [comment]
Sounds great to me!
