### ISSUE TITLE
Init_chain should return the genesis root hash and have post genesis hooks

### ISSUE THREAD

**Issue by theochap** [Sovereign-Labs/sovereign-sdk#555]
**Context**
Currently, the `init_chain` function does not return the initial root hash after genesis. This forces us to use hacks and process an empty blob such as in the demo-rollup. Moreover, the rollup needs to be able to get the initial state hash to properly initialize the chain state.

**Solution**
- Return the initial root hash after genesis in the `init_chain` function.
   - Done as part of #598 
- Hook on the exit of the init_chain function to be able to store the initial root hash. That would be some sort of genesis_hook.

**Comment by citizen-stig** [comment]
@theochap could you please confirm if this issue is still have left things to do?

**Comment by citizen-stig** [comment]
Already one!
