### ISSUE TITLE
EVM: Prepare the execution environment for `eth_call`

### ISSUE THREAD

**Issue by bkolad** [Sovereign-Labs/sovereign-sdk#576]
## Description

The `eth_call` API allows for the immediate execution of a new message call without creating a transaction on the blockchain. However, before the transaction is executed, it is essential to initialize the environment for the transaction. The relevant logic for this initialization can be found in the following location: [code](https://github.com/paradigmxyz/reth/blob/d8677b4146f77c7c82d659c59b79b38caca78778/crates/rpc/rpc/src/eth/revm_utils.rs#L201)

## Acceptance Criteria

Transaction is executed in an initialized environment and the relevant logic is unit tested.

**Comment by bkolad** [comment]
All the block-related data will be added after https://github.com/Sovereign-Labs/sovereign-sdk/issues/737 is done.

**Comment by bkolad** [comment]
Tthe only remaining field that needs to be filled is `access_list` in `prepare_call_env`

**Comment by LukaszRozmej** [comment]
We still need a bit more complex logic, but we are close: https://github.com/paradigmxyz/reth/blob/a8e0880a98142cc339c7d6c6e9d060082094e764/crates/rpc/rpc/src/eth/revm_utils.rs#L276-L317

**Comment by orkunkilic** [comment]
Let's close this @bkolad
