### ISSUE TITLE
sov-modules: Add iteration support for `StateMap`.

### ISSUE THREAD

**Issue by bkolad** [Sovereign-Labs/sovereign-sdk#61]
At this moment there is no way to iterate over all elements in `StateMap`.
Things to consider:
- All elements in the same `StateMap` share part of the prefix.
- Some elements of the map can be already in the `StateMap` cache but others exists only in the db. The iterator should know how to handle it.

**Comment by neysofu** [comment]
@bkolad why did we mark this as completed?
