### ISSUE TITLE
Unify `StorageKey` and `CacheKey`

### ISSUE THREAD

**Issue by vlopes11** [Sovereign-Labs/sovereign-sdk#643]
## Description

Currently, [StorageKey](https://github.com/Sovereign-Labs/sovereign-sdk/blob/01375688fcf719c5e20f32302374c70469e4dd3e/module-system/sov-state/src/storage.rs#L15-L19) and [CacheKey](https://github.com/Sovereign-Labs/sovereign-sdk/blob/01375688fcf719c5e20f32302374c70469e4dd3e/module-system/utils/sov-first-read-last-write-cache/src/lib.rs#L13-L16) are equivalent types. They historically were different, but as the implementation evolved, they converged to have the same. However, `StorageKey` implements serialization, whereas `CacheKey` doesn't.

This limits our implementation as the conversion between the types may force us to take the key as owned for simple operations such as get, when a reference should suffice

https://github.com/Sovereign-Labs/sovereign-sdk/blob/01375688fcf719c5e20f32302374c70469e4dd3e/module-system/sov-state/src/scratchpad.rs#L187

## Solution

Deprecate `CacheKey` and replace its usage by `StorageKey`. This will allow us to pass references downstream and make the map API more powerful, as the types are just borrowed references and can be passed downstream without any conversion. This will unlock a simplification requested on #427 

## Alternatives

We could unsafely cast one type to the other, but we have no clear gain to maintain the distinction and would create a potential undefined behavior if the layout of any of the types ever change. This would create a maintenance burden to cross-check both types whenever they are updated.

A working alternative suggested by @preston-evans98 is to use [yoke](https://crates.io/crates/yoke) to cast one type to the other. This will allow a zero-cost solution and will preserve both types, in case we want to maintain the distinction. The `CacheKey` is currently used for memory-only representation, and `StorageKey` is used for serialization. It might be desirable to maintain this domain separation if we want to have a layer that don't interact with I/O.

**Comment by bkolad** [comment]
We could even have a single type `StoargeSlot` for keys and values.

**Comment by citizen-stig** [comment]
As discussed on today's daily:

 * Keep `Key` and `Value` types for semantic
 * Rename `CacheKey` and `CacheValue` to `SlotKey` and `SlotValue`
 * Remove `StorageKey` and `StorageValue` in favour of `SlotKey`(previously `CacheKey`) and `SlotValue` (previously `CacheValue`)
