### ISSUE TITLE
`rewarded_address` in `StateTransition` is hard coded

### ISSUE THREAD

**Issue by citizen-stig** [Sovereign-Labs/sovereign-sdk#647]
As for today, reward address is hard coded to be address of sequencer. 

There are couple problems with it:

* Impossibility to have rewards to be sent to different address rather than sequencer.
* It is unclear if rewards are DA layer currency or Rollup currency. If it is rollup currency, then it should be rollup address.

Original PR: https://github.com/Sovereign-Labs/sovereign-sdk/pull/598

**Comment by theochap** [comment]
I don't have strong opinions about what the reward address should be. I think it should indeed be dynamic instead of hardcoded (specially for the based sequencing feature), and when it comes to the currency I think it doesn't really matter (but need to double check with @preston-evans98 )

**Comment by preston-evans98** [comment]
Yep, the rewarded address should definitely be dynamic. And it doesn't matter to me which format it is in - either a DA address or the corresponding rollup address is fine. Whichever is most natural for the module that needs to consume it.
