### ISSUE TITLE
`get_all` method for StateVec

### ISSUE THREAD

**Issue by orkunkilic** [Sovereign-Labs/sovereign-sdk#763]
**Is your feature request related to a problem? Please describe.**
In order to retrieve full statevec, we need to for loop all the statevec in module.

**Describe the solution you'd like**
It would be nice to have .get_all() that returns the StateVec as Vec.

**Additional context**
Does it make sense to have this built-in method for DevEx? @neysofu

**Comment by neysofu** [comment]
Hey,
we don't have a `.get_all()` but we do have an `.iter()`, which you can then `.collect()` and it does the same thing:

https://github.com/Sovereign-Labs/sovereign-sdk/blob/d66b9a00e717d876dbdc61467c00fce49c0a777f/module-system/sov-state/src/vec.rs#L302

**Comment by orkunkilic** [comment]
> Hey, we don't have a `.get_all()` but we do have an `.iter()`, which you can then `.collect()` and it does the same thing:
> 
> https://github.com/Sovereign-Labs/sovereign-sdk/blob/d66b9a00e717d876dbdc61467c00fce49c0a777f/module-system/sov-state/src/vec.rs#L302

I wasn't aware of this! Sorry

Closing the issue
