### ISSUE TITLE
Introduce module for tracking sequencer registration attempts

### ISSUE THREAD

**Issue by citizen-stig** [Sovereign-Labs/sovereign-sdk#788]
In order to remove "at least 1 honest sequencer" limitation from current design, following approach must be implemented.

If all sequencers censor transaction, user has ability to register as sequencer themself. For this they submit a batch to DA layer, where first transaction is `SequencerRegistry::Register` message, and rest of the blob is arbitrary bytes payload. This payload essentially represent cost of DA layer transaction. 

But in order to avoid DoS attack vector, rollup should dynamically track what is required size of this payload, depending on how much demand for "bootstrap" registration of new sequencers there are.

So this module should do this:

 ### 1. Have minimal size of payload, which is configured in genesis
 ### 2. Track how many bootstrap registrations happened in a slot. 
 
 For all batches that which are:
 
 1. Coming from non registered sequencer
 2. Total size is above currently required minimal blob size
 
 Module must **double** currently required minimal blob size if
 
 * Number of conditioned batches are equal or more than in previous slot
 
 Module must **half** currently required minimal blob size if
 
 * Number of conditioned batches are less than in previous slot

These checks happen independently from signature check.

 
 ### 3. Execute valid registrations 
 
If there are batches, that are above current size and their signature is valid, this module **should execute** this transaction via sov-sequencer module, so next blob from this user can be executed normally

Potential module names:

* Blob Tracker
* Sequencer Registration Tracker
* Registration Payload Tracker

**Comment by cemozerr** [comment]
Closing issue as it was implemented.
