### ISSUE TITLE
EVM: feature gate `DevSigner` & `send_Transaction` 

### ISSUE THREAD

**Issue by bkolad** [Sovereign-Labs/sovereign-sdk#839]
## Summary
Ethereum exposes the `send_Transaction` endpoint, which not only accepts a transaction but also signs it. However, it's not advisable to support this feature in a production environment because private key management should be handled by dedicated wallets. Nevertheless, many testing frameworks utilize the `send_Transaction` endpoint because it simplifies test setup.

To address this, we have introduced a  `DevSigner` within the eth sequencer. We should feature gate both the `DevSigner` and the `send_Transaction` endpoint so that they are only accessible during the development phase.

**Comment by orkunkilic** [comment]
I think we can close this @bkolad ?
