### ISSUE TITLE
EVM: Implement `eth_getTransactionCount` endpoint.

### ISSUE THREAD

**Issue by bkolad** [Sovereign-Labs/sovereign-sdk#882]
## Summary
Implement the endpoint according to the Ethereum spec.

**Comment by orkunkilic** [comment]
What do you think about historical nonce (getting transaction count on block N)? I believe it is not available on sov-evm implementation.
https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_gettransactioncount

**Comment by bkolad** [comment]
Let's implement it for `latest` for now and we will add the historical nonce functionality once we have the archival node. What do you think?
