### ISSUE TITLE
Move `GenesiConfig` and corresponding tests to `genesis.rs`

### ISSUE THREAD

**Issue by bkolad** [Sovereign-Labs/sovereign-sdk#993]
## Summary
Move tests  for genesis serialization logic to `lib.rs` 
See: https://github.com/Sovereign-Labs/sovereign-sdk/pull/990#discussion_r1348538397

**Comment by citizen-stig** [comment]
For clarity:

Placing tests in a top-level src/tests.rs file can mistakenly lead us to add what seems like integration tests. However, these might not truly be integration tests. For instance, they might depend on a private API, making the module ineffective.

To avoid this, unit tests should be alongside the functionality they test.

Regarding the situation in [#990 comment](https://github.com/Sovereign-Labs/sovereign-sdk/pull/990#discussion_r1348538397), we could consider moving the config struct from lib.rs to genesis.rs. By re-exporting it, all genesis-related tests would be in genesis.rs.
